const routerx = require("express-promise-router")
const authRouter = require("./authRouter")
const configRouter = require("./configRouter")
const userRouter = require("./userRouter")
const gameRouter = require("./gameRouter")
const promoRouter = require("./promoRouter")
const sportRouter = require("./sportRouter")
const walletRouter = require("./walletRouter")
const tournamentRouter = require("./tournamentRouter")
const loyaltyRouter = require("./loyaltyRouter")
const integrationRouterCG = require("./integrationRouterCG")
const integrationRouterBO = require("./integrationRouterBO")
const bonusRouter = require("./bonusRouter")
const limitsRouter = require("./limitsRouter")

const Router = routerx()

Router.use("/auth", authRouter)
Router.use("/config", configRouter)
Router.use("/user", userRouter)
Router.use("/game", gameRouter)
Router.use("/wallet", walletRouter)
Router.use("/promo", promoRouter)
Router.use("/sport", sportRouter)
Router.use("/tournament", tournamentRouter)
Router.use("/loyalty", loyaltyRouter)
Router.use("/integrationcg", integrationRouterCG)
Router.use("/integrationbo", integrationRouterBO)
Router.use("/bonus", bonusRouter)
Router.use("/limits", limitsRouter)

module.exports = Router
